Revamp resources pages (following new design)
DecouvreBitcoin/sovereign-university pull request #245
Opened 2024-04-05 15:16 UTC by kevinmulier

2024-04-08 14:31 UTC, trigger67 requested changes

2024-04-08 14:31 UTC, trigger67 commented on apps/web/src/features/resources/components/DropdownMenu/dropdown-menu.tsx
> +export const ResourcesDropdown = ({
I do not like having the name of the component not matching the name of the file.

2024-04-08 15:04 UTC, louneskmt commented on apps/web/src/features/resources/layout.tsx
> +      <div className={`flex h-fit justify-center p-2 md:p-10 ${className}`}>
Use the `cn` utility from our ui package to merge classes. Only commenting here but I've seen other occurrences.

2024-04-10 06:50 UTC, trigger67 approved these changes

2024-04-10 06:54 UTC, trigger67 commented
Bug: the "resource header" is also displayed in the professors page. @kevinmulier can you fix it?

2024-04-10 15:55 UTC, merged