fix(blogs): fixed sync function for blog tags
DecouvreBitcoin/sovereign-university pull request #711
Opened 2024-10-28 14:02 UTC by Flashmaxi

2024-10-28 14:52 UTC, trigger67 commented
What is the issue you are fixing with this PR?

2024-10-28 17:34 UTC, Flashmaxi commented
@trigger67 well when I wrote the function tags were not updating correctly as stated, so now when you sync with this update of function all tags are updated correctly and there are not extra (old) tags there.

2024-10-30 08:50 UTC, trigger67 commented
I updated one tag in the repo, and instead of updating it in my DB,,  the sync kept it and added a new one, now there are three tags instead of two.

Also you added insertion of tags in the localized files (in `createUpdateBlogs`), but they are already inserted in the `createProcessMainFile` as tags are the same for all languages.

Please read the code, understand how the sync process works for blogs, and rework this PR.

2024-10-30 16:06 UTC, trigger67 commented
I did run this locally, after the sync I have zero tags remaining in my DB, everything is removed.

Also again, the same remark as before : 

> Also you added insertion of tags in the localized files (in createUpdateBlogs), but they are already inserted in the createProcessMainFile as tags are the same for all languages.

2024-10-31 08:34 UTC, trigger67 commented
You added the conditions that was removed in a previous commit.

`if (file.kind === 'renamed')` does never happen, this has te be removed, as it was before

Also the check of `if (['added', 'modified', 'renamed'].includes(file.kind)) {` has to be removed.

2024-10-31 08:34 UTC, trigger67 requested changes
As previous comment

2024-10-31 09:06 UTC, Flashmaxi reviewed
Done

2024-10-31 09:21 UTC, trigger67 commented
The code does not execute

2024-10-31 09:23 UTC, trigger67 commented
Also I prefer the old version, without the new variable `newTags`, with the toLowerCase directly in the insert statement

2024-10-31 09:42 UTC, trigger67 requested changes

2024-10-31 09:42 UTC, trigger67 commented on packages/service-content/src/lib/blogs/import/main.ts
> +      console.log('No file provided, exiting function early.');
No need for console.log, as in all other import files.
This is mainly just usefull for typescript, because removed files have another type.

2024-10-31 09:42 UTC, trigger67 commented on packages/service-content/src/lib/blogs/import/main.ts
> +    const blogId = result.id;
Please add an empty line before that, to be more readably

2024-10-31 09:42 UTC, trigger67 commented on packages/service-content/src/lib/blogs/import/main.ts
> +    SELECT ${blogId}, id
You changed indentation on all three queries.
Best is like before: have one more tab than the above `await transaction`
Plus add one tab on sub parts of the query (what is selected, what is inserted, what values, ...).

2024-10-31 10:44 UTC, trigger67 approved these changes

2024-10-31 10:44 UTC, merged