fix(course page): professor order
DecouvreBitcoin/sovereign-university pull request #761
Opened 2024-11-03 21:07 UTC by Flashmaxi

2024-11-04 11:18 UTC, kevinmulier requested changes

2024-11-04 11:18 UTC, kevinmulier commented on packages/service-content/src/lib/courses/services/get-course.ts
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
don't use any

2024-11-05 08:47 UTC, kevinmulier commented
There seems to be a type mismatch between what is expected for professors in the getCourse query (FormattedProfessor[]) and what we really get out of it (string[])

Root of the problem is deeper than anticipated, I will check to see why that is happening and figure out a solution

2024-11-05 08:50 UTC, Flashmaxi commented
Yes, root of the problem is much deeper. I think it will take a lot of rewritting, is it possible to merge this change so we fix the ordering issue and than refactor code on different issue?

2024-11-07 08:25 UTC, trigger67 approved these changes

2024-11-07 08:25 UTC, merged