fix(calendar): calendar adjustments
DecouvreBitcoin/sovereign-university pull request #866
Opened 2024-11-25 09:18 UTC by Flashmaxi

2024-11-25 17:38 UTC, kevinmulier requested changes
Weird bug when going over some events 
[Capture vidéo du 25-11-2024 18:34:54.webm](https://github.com/user-attachments/assets/3eef3331-7216-4cbf-88ca-a83aa93606a5)

Impossible to read some events info
![image](https://github.com/user-attachments/assets/d67c370b-8452-433e-bfe9-4dcc8bc30453)

2024-11-25 17:38 UTC, kevinmulier commented on apps/web/src/components/Calendar/custom-event-month.tsx
> +  console.log('Event:', event);
Remove console log

2024-11-26 08:50 UTC, kevinmulier commented
![image](https://github.com/user-attachments/assets/a507fbff-06d8-4503-818b-4cdfe9862f9c)
bug still appears, can't read info when cards are on the end/they are too small

2024-11-26 09:17 UTC, Flashmaxi commented
> ![image](https://private-user-images.githubusercontent.com/48089250/389867551-a507fbff-06d8-4503-818b-4cdfe9862f9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTE1MTYsIm5iZiI6MTczMjYxMTIxNiwicGF0aCI6Ii80ODA4OTI1MC8zODk4Njc1NTEtYTUwN2ZiZmYtMDZkOC00NTAzLTgxOGItNGNkZmU5ODYyZjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA4NTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3M2JjOTEwMTg0MDUwMzFiNGNmNGIwNTA5M2IwMDZkMDk3MTk1Y2RmOGQ3OTU2NjYyNDliYzE4YmFkZjVlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0QbdWE3b_b9c5-pgHKZPZmwbieqUK_xs4f1CgwBIpl4) bug still appears, can't read info when cards are on the end/they are too small

I  think for now until we figure out different solution we need to keep it like this, I plan to keep this as ticket to try to improve react big calendar even more and if I figure out solution I will implement it. At the moment only PM/AM is not visible and I think that is not super relevant since we have calendar only on desktop at the moment and people are clicking on events and opening full detail event card.

2024-11-26 09:23 UTC, merged