seo: improvements for tutorials
DecouvreBitcoin/sovereign-university pull request #938
Opened 2024-12-06 14:21 UTC by Flashmaxi

2024-12-06 16:35 UTC, kevinmulier commented
![image](https://github.com/user-attachments/assets/46ec0862-33fb-478c-bd41-ca3dbe3313c2)
it should be name-id instead, like for other resources -> 
![image](https://github.com/user-attachments/assets/e3b6f31b-1800-4e03-8e8f-0e0ec3d63417)

2024-12-09 15:26 UTC, trigger-xyz requested changes
Links in the TutorialCard component has not been updated, thus do not work anymore

2024-12-09 15:37 UTC, Flashmaxi commented
> Links in the TutorialCard component has not been updated, thus do not work anymore

Updated TutorialCard links in the component and professors page.

2024-12-09 15:51 UTC, trigger67 approved these changes

2024-12-09 15:52 UTC, merged